# Cloudflare Pages configuration
name = "arbme-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[env.production]
vars = { VITE_API_URL = "https://arbme-api.dylan-259.workers.dev" }

[env.preview]
vars = { VITE_API_URL = "https://arbme-api.dylan-259.workers.dev" }
