[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = [
  "cd ../..",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd ../.. && pnpm --filter @arbme/core-lib build"
]

[start]
cmd = "cd packages/bot && pnpm start"
